version: '3.9'
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: app
    restart: unless-stopped
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn src.app:app --host 0.0.0.0 --port 8000'
